title: "Intro to Jupyter Book"
author: "Syahrul Hamdani"
logo: "assets/images/logo.png"

# repository
repository:
  url: "https://github.com/syahrulhamdani/teaching-using-jupyter-book"
  path_to_book: "example"
  branch: "main"

# html config
html:
  favicon: "assets/images/logo.png"
  use_repository_button: true
  use_issue_button: true

# notebook launcher
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"

# references
bibtex_bibfiles:
  - references.bib

# sphinx configuration
sphinx:
  config:
    bibtex_reference_style: author_year
